Fix TypeError: unhashable type: 'PersistentMapping' in safe_write.
This happens at least in the tests, since I have added code in setuphandlers to activate plugin interfaces.

```
Error in test test_remember_identity (pas.plugins.oidc.tests.test_plugin.TestPlugin)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/3.8.13/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/Users/maurits/.pyenv/versions/3.8.13/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.pyenv/versions/3.8.13/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/Users/maurits/clients/vmm/kennis-plone60/checkouts/pas.plugins.oidc/src/pas/plugins/oidc/tests/test_plugin.py", line 30, in test_remember_identity
    self.plugin.rememberIdentity(userinfo)
  File "/Users/maurits/clients/vmm/kennis-plone60/checkouts/pas.plugins.oidc/src/pas/plugins/oidc/plugins.py", line 132, in rememberIdentity
    with safe_write(self.REQUEST):
  File "/Users/maurits/.pyenv/versions/3.8.13/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/maurits/clients/vmm/kennis-plone60/checkouts/pas.plugins.oidc/src/pas/plugins/oidc/plugins.py", line 321, in safe_write
    objects_before = set(_registered_objects(request))
TypeError: unhashable type: 'PersistentMapping'
```

When I go in with a pdb, I get this:

```
(Pdb) _registered_objects(request)
[<Persistence.mapping.PersistentMapping object at 0x10ce1bc80 oid 0x1f5a256f1c5f06f4 in <Connection at 10ccbec40>>]
(Pdb) set(_registered_objects(request))
*** TypeError: unhashable type: 'PersistentMapping'
(Pdb) !list(_registered_objects(request)[0].items())
[(<InterfaceClass Products.PluggableAuthService.interfaces.plugins.IExtractionPlugin>, ('credentials_cookie_auth', 'credentials_basic_auth', 'session')), ...]
```

Not sure if this can happen in practice on a live site as well.  But the traceback shows that `set` does not work on all registered objects, so we had better not use it.